"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import RivenOrchestrationDashboard from "./components/RivenOrchestrationDashboard";
const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL||"";
export default function Home(){const[query,setQuery]=useState("");const[run,setRun]=useState(null);const[events,setEvents]=useState([]);const[error,setError]=useState("");const[executing,setExecuting]=useState(false);const[system,setSystem]=useState(null);const[documents,setDocuments]=useState([]);const[sources,setSources]=useState([]);const sourceRef=useRef(null);
async function refreshDocuments(){const r=await fetch(`${API_BASE}/api/documents`);if(r.ok)setDocuments(await r.json())}
useEffect(()=>{fetch(`${API_BASE}/api/system/status`).then(r=>r.ok?r.json():null).then(setSystem).catch(()=>setSystem(null));refreshDocuments().catch(()=>{});return()=>sourceRef.current?.close()},[]);
const agentStates=useMemo(()=>{const m=new Map();for(const t of run?.tasks||[])m.set(t.agent_id,{...t,latest:t.status||"assigned"});for(const e of events){if(!e.agent_id)continue;const c=m.get(e.agent_id)||{agent_id:e.agent_id};m.set(e.agent_id,{...c,latest:e.type,message:e.message})}return[...m.values()]},[run,events]);
const liveWebSources=useMemo(()=>events.filter(e=>e.type==="source.found"&&e.metadata?.origin==="web"),[events]);
async function previewEvidence(){if(query.trim().length<2)return;try{const r=await fetch(`${API_BASE}/api/sources/search?q=${encodeURIComponent(query)}&limit=6`);if(r.ok)setSources(await r.json())}catch{}}
async function startResearch(ev){ev.preventDefault();setError("");setEvents([]);setExecuting(true);sourceRef.current?.close();try{await previewEvidence();const r=await fetch(`${API_BASE}/api/runs`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query})});if(!r.ok)throw new Error("Could not create research run.");const nr=await r.json();setRun(nr);const s=new EventSource(`${API_BASE}/api/runs/${nr.id}/events`);sourceRef.current=s;s.onmessage=m=>setEvents(c=>[...c,JSON.parse(m.data)]);s.onerror=()=>setError(c=>c||"Live event stream disconnected.");const x=await fetch(`${API_BASE}/api/runs/${nr.id}/execute`,{method:"POST"});if(!x.ok){const b=await x.json().catch(()=>({}));throw new Error(b.detail||"Research execution could not start.")}setRun(await x.json())}catch(e){setError(e.message||"Research execution failed.")}finally{setExecuting(false)}}
return <RivenOrchestrationDashboard system={system} documents={documents} sources={sources} query={query} setQuery={setQuery} startResearch={startResearch} executing={executing} error={error} run={run} events={events} agentStates={agentStates} liveWebSources={liveWebSources}/>}
